name: Run Low IV Stock Scanner

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy

    - name: Run scanner script
      run: |
        python low_iv_stock_scanner.py || echo "Script failed, creating empty output" > output.txt

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: low-iv-results
        path: output.txt
